[project]
name = "bluetooth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.18"
dependencies = [
    "pybluez",
    "setuptools==57.5.0",
]

[tool.uv.sources]
pybluez = { git = "https://github.com/pybluez/pybluez.git" }
